### ISSUE TITLE
Create process to make sure new changes don't break existing code

### ISSUE THREAD

**Issue by SarinaAtkinson-NOAA** [SarinaAtkinson-NOAA/SEFSC-ODM-Management-History#10]
Identify test clusters from SEDAR working papers.
Add as its own script.
Save results as .Rdata? So we have something static to compare to.
use comparedf()

**Comment by SarinaAtkinson-NOAA** [comment]
use comparedf()

**Comment by SarinaAtkinson-NOAA** [comment]
@AdyanRios-NOAA take at look at this workflow and we can discuss it next week. 
Steps:

1. In main_MH_prep added line at the end to save R environment as a .RData file once all MH steps have been ran (00-05). This .RData is saved with a date in the filename so we do not overwrite each time.
2. Created folder called "test" 
3. Within test folder, we have scripts to create the test.RData file (currently only has 2 clusters) and another script to compare test to our recent analysis ready dataset.
4. All the MH_test_process.R script does is load in our .RData files, subset analysis ready for clusters in test, run compare_df, and if differences, visualize in viewer as a table.

The compareDF package is great and I particularly love the [create_output_table()](https://github.com/alexsanjoseph/compareDF) function. It does everything we need so we can keep the script short!

**Comment by AdyanRios-NOAA** [comment]
Will do ahead of our next meeting!

**Comment by AdyanRios-NOAA** [comment]
Should we move librarian::shelf() to the top, and adding other packages (here, tidyverse, etc), so that they can be run stand alone in a fresh R environment, without any running other scrips first?

**Comment by AdyanRios-NOAA** [comment]
I know we had agreed to .RData files, but I just remembered that RDS files are better for this purpose. That way when they are read in you intentionally name a single object. When you read in RData files for a single object, the object's name is somewhat less obvious. We can chat more about this on Friday.

**Comment by AdyanRios-NOAA** [comment]
Is cluster 365 validated/approved? 365 is a South Atlantic Red Snapper cluster, not one of the ones included in the MH ODM [red snapper working paper ](chrome-extension://efaidnbmnnnibpcajpcglclefindmkaj/https://sedarweb.org/documents/sedar-74-dw-25-summary-of-management-actions-for-red-snapper-lutjanus-campechanus-from-the-gulf-of-mexico-1984-2022-as-documented-within-the-management-history-database/)(Gulf of Mexico).

**Comment by SarinaAtkinson-NOAA** [comment]
Updated workflow to save to RDS rather than RDATA.
