### ISSUE TITLE
Address recurring regulations

### ISSUE THREAD

**Issue by SarinaAtkinson-NOAA** [SarinaAtkinson-NOAA/SEFSC-ODM-Management-History#11]
Now that #10 is done, we can use the test cases to compare to as we make changes to the code.

**Comment by AdyanRios-NOAA** [comment]
I will try to think about this more ahead of next Friday. To build up to this I think I will just explore the working papers for a handful of cluster of a recurring reg type that were already explored in depth in the working papers.

Thinking more about recurring regulations, the topic of multi-reg also comes to mind (regulations that co-exist and do not overwrite). That might be a good next issue or discussion to create. I wonder if this is already part of the skip-to-an-earlier-reg logic when flagged, but I don't recall.

**Comment by SarinaAtkinson-NOAA** [comment]
What do we want to do about recurring regulations. Below is showing the automated recurring closure table for Gulf red snapper (cluster 306)
![image](https://user-images.githubusercontent.com/71387505/212187094-619bf70f-dc03-4fa4-b1f7-8349fa2781b5.png)

And this is the working paper table:
![image](https://user-images.githubusercontent.com/71387505/212187158-3ea86428-7ac1-44a8-a8c3-0d8e2250a280.png)

They are not far off and in this first stage of processing, I do not think we need to expand to every month within the timeframe for monthly recurring closures.

**Comment by SarinaAtkinson-NOAA** [comment]
The code for expanding a recurring closure to the actual months/days that are closed is something we will need to address AFTER we give this code to Yanet. This step will be a part of the daily analysis-ready dataset which will actually be used for analyses. The printed analysis ready tables are intended to show the start and end dates for the FRs comprehensively between the time series. It is not meant to show the expanded dates.

BUT the start and end dates are not working yet for this example above for monthly recurring closures. 
ALSO we need to remove the record in the table that are turning off the regulation (see example above for seasonal closures)

**Comment by SarinaAtkinson-NOAA** [comment]
For this first phase of automation, recurring closures are ok.
