### ISSUE TITLE
Idea to include fishing year as fields in all clusters

### ISSUE THREAD

**Issue by SarinaAtkinson-NOAA** [SarinaAtkinson-NOAA/SEFSC-ODM-Management-History#15]
Consider adding the fishing season as  fields in the all clusters because 1) it will help with processing for ACLS and 2) cluster 1030 has an issue with a closure for FR 80 FR 25966 where the fishing season is factored into when the closure ends. Right now fishing season is not considered which means the dates don't line up with what we have in the working paper.

**Comment by AdyanRios-NOAA** [comment]
UNIQUE STARTS look OK except for a situation with: 
July1-May1 (could be mistaken 7 for a 6, TBD)

**Comment by AdyanRios-NOAA** [comment]
When merging in the fishing year start month and start day, we will need to merge first by FMP (all) first, because not all regulations will be all, some might be species specific. Then also merge in species specific fishing year information when that exists.

**Comment by AdyanRios-NOAA** [comment]
- [ ] Deal with single example of a non-365 day fishing year as a data bug. Enter as data bug change from a "fishing year" to "closure".

**Comment by AdyanRios-NOAA** [comment]
FOR THE MERGE WE WILL NEED: 
YEAR, FMP, SPP_NAME, FY_START_DAY, FY_START_MONTH
also FY_START_DATE

THEN MERGE FOR FISHING YEAR ALL
THEN MERGE FOR FISHING YEAR NOT ALL

**Comment by AdyanRios-NOAA** [comment]
Consider adding reopening associated with star of fishing seasons and years

**Comment by AdyanRios-NOAA** [comment]
Look into "QUOTA"   "ACL" and "MSST" when Start year is missing. @SarinaAtkinson-NOAA

**Comment by AdyanRios-NOAA** [comment]
There is also a case of  "TRIP LIMIT" multi-reg that we need to factor in fishing year start month and start day. @AdyanRios-NOAA

**Comment by SarinaAtkinson-NOAA** [comment]
Fishing season - 42 unique clusters
Caribbean spiny lobster is the only species where there are fishing season for specific subsectors
Only 7 clusters flagged for multi-reg which assumes we have 2 fishing seasons in a year. Those clusters being

- COASTAL MIGRATORY PELAGIC RESOURCES - MACKEREL, KING - COMMERCIAL
- REEF FISH RESOURCES OF THE GULF OF MEXICO - SNAPPER, RED - COMMERCIAL
- SNAPPER-GROUPER FISHERY OF THE SOUTH ATLANTIC REGION - AMBERJACK, GREATER - COMMERCIAL
- SNAPPER-GROUPER FISHERY OF THE SOUTH ATLANTIC REGION - GROUPER, SNOWY - COMMERCIAL
- SNAPPER-GROUPER FISHERY OF THE SOUTH ATLANTIC REGION - PORGY, RED - COMMERCIAL
- SNAPPER-GROUPER FISHERY OF THE SOUTH ATLANTIC REGION - TRIGGERFISH, GRAY - COMMERCIAL
- SPINY LOBSTER FISHERY OF THE GULF OF MEXICO AND SOUTH ATLANTIC - LOBSTER, CARIBBEAN SPINY - RECREATIONAL

Suggest we run the same process on fishing season, with FS1_START_MONTH, FS1_START_DAY, FS2_START_MONTH, and FS2_START_DAY

**Comment by SarinaAtkinson-NOAA** [comment]
Suggestion by @AdyanRios-NOAA where fishing year/season is used for closures and reopenings, we should default the fishery to open at the start of the fishing year/season.

**Comment by SarinaAtkinson-NOAA** [comment]
Fishing year is incorporated now and checks are creating along the way to stop the process from running if we have duplicates or records missing fishing year that should have one
