### ISSUE TITLE
Migrate working clean code to SEFSC repo

### ISSUE THREAD

**Issue by SarinaAtkinson-NOAA** [SarinaAtkinson-NOAA/SEFSC-ODM-Management-History#4]
- [X] Add all R scripts - Adyan
- [X] Create loop for static cluster IDs - Adyan
- [x] Create loop for cluster IDs - Adyan
- [x] Test - Sarina & Adyan

**Comment by SarinaAtkinson-NOAA** [comment]
@AdyanRios-NOAA I am testing the changes you made now in creating loops to get static IDs. However, I know you ran this already, shouldn't I be using your interim/clusters and interim/sector_clusters files? When I pulled, these folders and files were not created but I believe you should push those changes so we are starting from the same ID list.

**Comment by AdyanRios-NOAA** [comment]
Good catch @SarinaAtkinson-NOAA! 

I just pushed those files. I still think we have a couple changes before static IDs can be considered final. For example, we only have the spatial clean up in the processing code for the Gulf Reef Fish FMP. There might be additional clusters IDs reassigning that result from spatial clean up. That said, those spatial synonyms are somewhat rare.

**Comment by SarinaAtkinson-NOAA** [comment]
@AdyanRios-NOAA might want to redo the cluster and sector ID file. When I ran the code again after I pulled in your changes, I am getting 22 new sector and cluster IDs. Why is this when the raw data file has not changed?

**Comment by SarinaAtkinson-NOAA** [comment]
@AdyanRios-NOAA the following changes were made and pushed up to Github

- Replaced MH csv file with latest download
- Added encoding type to read.csv command
- Created new static and cluster IDs
- Renamed cluster_max in the sector ID script to sector_max so it does not get overwritten by clutsterID procedure
- Added code to remove grouping/summarizing warnings from dplyr

**Comment by SarinaAtkinson-NOAA** [comment]
Migrated via pull request!
