### ISSUE TITLE
Review adjusting end day

### ISSUE THREAD

**Issue by SarinaAtkinson-NOAA** [SarinaAtkinson-NOAA/SEFSC-ODM-Management-History#9]
### Discussed in https://github.com/SarinaAtkinson-NOAA/SEFSC-ODM-Management-History/discussions/8

<div type='discussions-op-text'>

<sup>Originally posted by **SarinaAtkinson-NOAA** November  3, 2022</sup>
https://github.com/SarinaAtkinson-NOAA/SEFSC-ODM-Management-History/blob/3d7504dbf2e5901321ee3c1b9c33c0d690329ce5/code/MH01_new_variables.R#L151

Why are we adjusting the end day to the prior day for only STATUS_TYPE == "RECURRING"?
How are cases when the day = 1 being adjusted to the prior day being the last day of the previous month?</div>

**Comment by SarinaAtkinson-NOAA** [comment]
Reorder all of the mutates to create start date and end date to have smarter, more understandable code. Create a check to summarize the changes and overwriting of dates so we know what changes were made.

Reg 858 example we can test.

**Comment by SarinaAtkinson-NOAA** [comment]
I don't know that we need to create NEW_START_TIME, NEW_ND_DAY, and NEW_END_TIME anymore.

**Comment by SarinaAtkinson-NOAA** [comment]
@AdyanRios-NOAA will tackle the start and end day of the week add/subtract issue

**Comment by AdyanRios-NOAA** [comment]
I found a forcats function that I thought would do the trick, but it more related to reordering for visuals. I could not find how to shift a factor by one. So I wrote code to do it. It is not very slick, but it works. I am going to put it into a branch to see what we think.

**Comment by AdyanRios-NOAA** [comment]
**Create an ordered factor**
x <- factor(c("Mon", "Tue", "Wed"),
  levels = c("Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"),
  ordered = TRUE)

x
[1] Mon Tue Wed
Levels: Sun < Mon < Tue < Wed < Thu < Fri < Sat

**Convert to numeric:**
y = as.numeric(x)

y
[1] 2 3 4

**Add one to everyone:**
z = y+1

z
[1] 3 4 5

**Redefine ordered factor (one level lower)**
i = z
i[1] = i[1]-1

i
[1] 2 4 5

**Return to Factor**
j = factor(i,   
levels = c("1", "2", "3", "4", "5", "6", "7"),
ordered = TRUE)

j
[1] 2 4 5
Levels: 1 < 2 < 3 < 4 < 5 < 6 < 7

**Return to days of the week:**
k=j
levels(k) = c("Sat", "Sun", "Mon", "Tue", "Wed", "Thu", "Fri")

k
[1] Sun Tue Wed
Levels: Sat < Sun < Mon < Tue < Wed < Thu < Fri

**Comment by AdyanRios-NOAA** [comment]
@SarinaAtkinson-NOAA 

If you get a chance to review my latest [commit ](https://github.com/SarinaAtkinson-NOAA/SEFSC-ODM-Management-History/commit/6c284992d5083450d4743a0d24a06125afddff1b) and to practice branch merges ahead of Friday please give it a shot! The changes should make sense with the notes in the code.

[recode_factor()](https://dplyr.tidyverse.org/reference/recode.html)ended up being a somewhat ok solution! A bit cleaner than what I had suggested in the comment above.
